### ISSUE TITLE
Aboutの趣味のゴママヨのリンクが切れている

### ISSUE THREAD

**Issue by futchitwo** [ThinaticSystem/thinaticsystem.com#33]
https://thinaticsystem.com/vocabulary/gomamayo になってる

## 修正方法
- リンクを /glossary/gomamayo に書き換える
- glossary ディレクトリを /vocabulary に置き換える
  - 他のサイトからも参照されているので、置き換えた場合は /glossary ディレクトリからのリダイレクトを設定した方がいい

**Comment by CookieRamen** [comment]
@futchitwo @ThinaticSystem この部分はCMSで管理してるので修正かけました

**Comment by ThinaticSystem** [comment]
手を合わせる絵文字
